### ISSUE TITLE
Emojione are uppercase

### ISSUE THREAD

**Issue by sonicviz** [lookback/meteor-emoji#1]
I found the Emojione links would show as broken images because the files are all uppercase, unlike the twitter ones which are lc. Also, is there by any chance an emoji picker available for meteor?

**Comment by johanbrook** [comment]
I don't think that's something this package can accommodate for.

**Comment by sonicviz** [comment]
I figured that, but you may want to update the documentation re: uppercase emojione files. In any event there is an official emojione package on Atmosphere as well.
