### ISSUE TITLE
Emojis showing as question marks in Google Chrome

### ISSUE THREAD

**Issue by chrisjd20** [lookback/meteor-emoji#5]
Having an issue rendering emojis. 

When I simply statically set the emojis in a div and use the {{#emojis}} tag, It works fine:
![image](https://user-images.githubusercontent.com/11812223/29758115-fc1d4198-8b7e-11e7-8b83-cc31b2259122.png)

See it rendered:

![image](https://user-images.githubusercontent.com/11812223/29758119-03cdfd88-8b7f-11e7-84e4-59ae5135438f.png)

However, when I put the emojis in a for loop for messages being rendered, it doesn't work:

![image](https://user-images.githubusercontent.com/11812223/29758287-2fe114f4-8b80-11e7-843b-838772201cb8.png)

This shows up as:

![image](https://user-images.githubusercontent.com/11812223/29758166-4e7937ee-8b7f-11e7-9fd3-e41ff644d15a.png)

**Comment by chrisjd20** [comment]
When I inspect the element, it shows up fine.

![image](https://user-images.githubusercontent.com/11812223/29758206-a41ac6b8-8b7f-11e7-990e-d8a3d667a316.png)

**Comment by chrisjd20** [comment]
More details, this issue arises only in Chrome. When I do it in Firefox, the emojis render properly:

**Comment by chrisjd20** [comment]
![image](https://user-images.githubusercontent.com/11812223/29758418-5e7a26ce-8b81-11e7-8f34-8ae54fde9119.png)

**Comment by chrisjd20** [comment]
I also completely cleared my cache. removed and reinstalled. Then updated Chrome. Still not working.

I can use this is practically any other browser. Even mobile chrome. However, my desktop version isnt rendering it.

**Comment by chrisjd20** [comment]
And its rendering some of the emoji's:

![image](https://user-images.githubusercontent.com/11812223/29759177-4ab3c9a0-8b87-11e7-919e-4e05ebbb6fac.png)

**Comment by johanbrook** [comment]
Hi Chris.

Hm, so it's not rendering when in a loop? Does it render correctly if you use the inline helper?

```
{{ > emoji message}}
```

**Comment by chrisjd20** [comment]
Thanks for the quick reply.

Changed it to:
![image](https://user-images.githubusercontent.com/11812223/29775054-c1712750-8bd1-11e7-9cd4-3c847edcff83.png)

Still showing question marks though. Just tried on two different desktop's using the newest version of Chrome.

Strange thing is if I inspect the element, it shows the emoji in the source:
![image](https://user-images.githubusercontent.com/11812223/29775137-ff11e9d2-8bd1-11e7-8167-5a3878f74555.png)

**Comment by chrisjd20** [comment]
Im wondering if its a conflict with some other css? Cause some of them do render properly.

![image](https://user-images.githubusercontent.com/11812223/29777039-9ef3e882-8bd8-11e7-8fba-0d7bd42a3c6a.png)

**Comment by johanbrook** [comment]
Hm, no emojis are simply glyphs like any other character in the computer's alphabet. Are you sure those emojis are supported by that browser on that OS? There are some inconsistencies in emoji sets between them, I've discovered.

**Comment by chrisjd20** [comment]
Im running Windows 10 with Chrome 64 bit. (super common)

![image](https://user-images.githubusercontent.com/11812223/29777239-4656adc6-8bd9-11e7-964a-b6b87ff167c7.png)

Also, wouldn't that stop the ones in that are statically set from rendering if it was browser specific?

![image](https://user-images.githubusercontent.com/11812223/29777272-74bfa3ac-8bd9-11e7-9cec-6237b0e182c0.png)

**Comment by chrisjd20** [comment]
So its loading when statically set but not in a loop.

**Comment by johanbrook** [comment]
> Also, wouldn't that stop the ones in that are statically set from rendering if it was browser specific?

Yea, emojis seem to work on you platform for sure :) 

Are you sure the `message` part is legit? The one you send to the emoji helper?

**Comment by chrisjd20** [comment]
What do you mean by legit? Its the field name for the current json object in the for loop.  It's how user messages populate:

![image](https://user-images.githubusercontent.com/11812223/29777465-16391966-8bda-11e7-8b43-f77c69648218.png)

**Comment by chrisjd20** [comment]
I feel It's gotta be something in the JS or thw way in which the JS in handled in Chrome when running it rhough the emoji helper because I can see it render fine in Firefox:

![image](https://user-images.githubusercontent.com/11812223/29777537-6bf1cccc-8bda-11e7-9444-ab57f079222a.png)

**Comment by johanbrook** [comment]
Right. This is really weird, and most likely a Chrome issue then.

**Comment by chrisjd20** [comment]
The only difference I can think of is that when set statically, its processing text:
![image](https://user-images.githubusercontent.com/11812223/29777813-4ccdb35a-8bdb-11e7-9924-47b7bd654247.png)

However, when passed:
![image](https://user-images.githubusercontent.com/11812223/29777831-5c771dbe-8bdb-11e7-91a0-e2a0f751634b.png)

Its passing a object. 

Not sure, I'll keep playing with it. However, My OS Browser combination is very common. I tried it on several desktops now with the same result. This may be something you want to look into otherwise your package is no good for like  70% of the browser market. 
![image](https://user-images.githubusercontent.com/11812223/29777952-c8aec392-8bdb-11e7-87dc-b6258445efab.png)

Considering 90% of people use Windows and 76% of them use Chrome.

**Comment by chrisjd20** [comment]
I don't mean to sound too critical. I love the package. You have done good work!

**Comment by johanbrook** [comment]
So does it work in Chrome/Win when:

```
{{#each comments}}
  {{#emoji}}Some text and an emoji: :boy:{{/emoji}}
{{/each}}
```

instead of 

```
{{#each comments}}
  {{#emoji}}{{{message}}}{{/emoji}}
{{/each}}
```

?

**Comment by chrisjd20** [comment]
Good point, ill check

**Comment by chrisjd20** [comment]
Oh wow weird. I placed that where the message should be but also outside the loop and it still did it. Being in different divs causes it to render differently?

![image](https://user-images.githubusercontent.com/11812223/29778622-02293cf4-8bde-11e7-8775-769d8b5b17a0.png)

**Comment by chrisjd20** [comment]
Oh wow, So I copied the exact static text thats working in the other div into this div and its still experiencing the same issue. 

Why would it being in two sepparate divs make a difference?

![image](https://user-images.githubusercontent.com/11812223/29778754-5f99511c-8bde-11e7-89bf-abba67eaeb6c.png)

**Comment by johanbrook** [comment]
Hum hum. I take you followed the stuff in the README.md file too? Like, you're subscribed to the emojis publication and that. What happens if you do

```js
Emojis.findOne({
  alias: 'smile'
});
```

in the JS console?

**Comment by chrisjd20** [comment]
Yup, and yup
![image](https://user-images.githubusercontent.com/11812223/29778950-0bc4601c-8bdf-11e7-81d3-81b7e1fdc90d.png)

![image](https://user-images.githubusercontent.com/11812223/29778957-142665d4-8bdf-11e7-895f-03b4e9d9067b.png)

**Comment by chrisjd20** [comment]
JS Console sees it fine.

**Comment by chrisjd20** [comment]
So I can position the emoji's in any other div and they render ok.
![image](https://user-images.githubusercontent.com/11812223/29779144-ac6fd3ca-8bdf-11e7-9ad7-7c306d9a021e.png)

But as soon as I position inside this div:
![image](https://user-images.githubusercontent.com/11812223/29779195-d0c6993e-8bdf-11e7-8bdb-a6b50e9d8f3a.png)

Doesnt work.
![image](https://user-images.githubusercontent.com/11812223/29779209-db8ce508-8bdf-11e7-8fb4-4d4b6156251f.png)


Sure it couldnt be css related?

**Comment by chrisjd20** [comment]
Here is the CSS for this div

![image](https://user-images.githubusercontent.com/11812223/29779382-6bb2105e-8be0-11e7-86ae-a9f66342f827.png)

**Comment by chrisjd20** [comment]
Ok this is weird as hell lol. I literally put nothing but those in the divs. It renders fine in the top but not on the bottom:
![image](https://user-images.githubusercontent.com/11812223/29780032-57b276b4-8be2-11e7-821d-b02b55fdfab7.png)

**Comment by chrisjd20** [comment]
FOUND IT!

The issue is:

word-wrap: break-word;

Soon as I removed that, it rendered just fine!

**Comment by chrisjd20** [comment]
![image](https://user-images.githubusercontent.com/11812223/29780300-58af03d8-8be3-11e7-842b-adb9ccaca8c1.png)

Ill have to figure out how to break it another way. Thanks for your help.

**Comment by johanbrook** [comment]
Ah, gotcha! It might break the emoji glyphs (for some reason) and make them un-renderable :O
